# from https://github.com/tripplet/Adium-Steam-IM/blob/master/.travis.yml
language: objective-c
before_install:
  - wget https://bitbucket.org/adium/adium/get/adium-1.5.10.tar.gz
  - mkdir adium
  - tar xf adium-1.5.10.tar.gz -C adium/ --strip-components=1
  - cd adium
  - xcodebuild -project Adium.xcodeproj
  - cd ..
branches:
  only:
    - master