# from https://github.com/tripplet/Adium-Steam-IM/blob/master/.travis.yml
language: objective-c
before_install:
  - wget https://bitbucket.org/adium/adium/get/adium-1.5.10.tar.gz > /dev/null 2>&1
  - brew update > /dev/null 2>&1
  - brew install libtool automake autoconf libsodium check glib > /dev/null 2>&1
install:
  - mkdir adium
  - tar xf adium-1.5.10.tar.gz -C adium/ --strip-components=1
  - cd adium
  - xcodebuild -project Adium.xcodeproj > /dev/null 2>&1
  - cd ..
  - cd ProjectTox-Core
  - autoreconf -i
  - ./configure
  - make
  - make install
  - cp toxcore/network.h /usr/local/include/tox
  - cd ..
  - xcodebuild -project ToxPlugin.xcodeproj
branches:
  only:
    - master